// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBq0u68uvuH1GNuwiWT5ZeSm7NS-YlhCjw',
    appId: '1:694079096161:web:f8f97043d12360d4a1b120',
    messagingSenderId: '694079096161',
    projectId: 'kayak-merkezi-app',
    authDomain: 'kayak-merkezi-app.firebaseapp.com',
    storageBucket: 'kayak-merkezi-app.firebasestorage.app',
    measurementId: 'G-2SZEPLJC1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWOXZPDsSQ3zacHKh5D8_pbdkBCz6dsBM',
    appId: '1:694079096161:android:b240bf92511880e8a1b120',
    messagingSenderId: '694079096161',
    projectId: 'kayak-merkezi-app',
    storageBucket: 'kayak-merkezi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhkcnXK3ARmGAISIMAVMplAJJNYsh3aCk',
    appId: '1:694079096161:ios:0804da329aea3c1aa1b120',
    messagingSenderId: '694079096161',
    projectId: 'kayak-merkezi-app',
    storageBucket: 'kayak-merkezi-app.firebasestorage.app',
    iosBundleId: 'com.example.kayakMerkeziApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhkcnXK3ARmGAISIMAVMplAJJNYsh3aCk',
    appId: '1:694079096161:ios:0804da329aea3c1aa1b120',
    messagingSenderId: '694079096161',
    projectId: 'kayak-merkezi-app',
    storageBucket: 'kayak-merkezi-app.firebasestorage.app',
    iosBundleId: 'com.example.kayakMerkeziApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBq0u68uvuH1GNuwiWT5ZeSm7NS-YlhCjw',
    appId: '1:694079096161:web:5b646b9493f59827a1b120',
    messagingSenderId: '694079096161',
    projectId: 'kayak-merkezi-app',
    authDomain: 'kayak-merkezi-app.firebaseapp.com',
    storageBucket: 'kayak-merkezi-app.firebasestorage.app',
    measurementId: 'G-K5FC1XCMQ3',
  );
}
